// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LinkedinPageTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void linkedinPage() {
    // Test name: LinkedinPage
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.google.com/");
    // 2 | setWindowSize | 1330x969 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1330, 969);
    // 3 | click | id=APjFqb | 
    driver.FindElement(By.Id("APjFqb")).Click();
    // 4 | click | css=#jZ2SBf > .wM6W7d > span | 
    driver.FindElement(By.CssSelector("#jZ2SBf > .wM6W7d > span")).Click();
    // 5 | click | css=.MjjYud:nth-child(4) .LC20lb | 
    driver.FindElement(By.CssSelector(".MjjYud:nth-child(4) .LC20lb")).Click();
  }
}
